# Generated by Django 5.2.8 on 2025-11-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Book Title')),
                ('slug', models.SlugField(blank=True, max_length=10, unique=True, verbose_name='URL Slug')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Publication Year')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Cover Image')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('full_text', models.TextField(blank=True, verbose_name='Full Book Test')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
